image:
  registry: docker.io
  repository: grafana/grafana
  tag: "12.3"

replicas: 1

testFramework:
  enabled: false

serviceAccount:
  create: false

env:
  GF_SERVER_ROOT_URL: https://localhost:8080/grafana
  GF_SERVER_SERVE_FROM_SUB_PATH: 'true'

ingress:
  enabled: true
  path: /grafana
  hosts:
  - ""

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service.prometheus-system.svc.cluster.local:9090
      access: proxy
      isDefault: true
